server:
  port: 8081
spring:
  h2:    console:      enabled: true
  config:    import: optional:configserver:http://localhost:8888
  application:
    name: ORDER-SERVICE-ASSIGN
        
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost