INSERT INTO order_table(ORDER_NO,CUSTOMER_ID,DATED,ORDER_AMOUNT,ORDER_STATUS,STORE_ID,STORE_NAME) values(100,200,sysdate(),2000,'PLACED',300,'storeA');
INSERT INTO order_table(ORDER_NO,CUSTOMER_ID,DATED,ORDER_AMOUNT,ORDER_STATUS,STORE_ID,STORE_NAME) values(101,200,sysdate(),3000,'SHIPPED',300,'storeB');
INSERT INTO order_table(ORDER_NO,CUSTOMER_ID,DATED,ORDER_AMOUNT,ORDER_STATUS,STORE_ID,STORE_NAME) values(102,201,sysdate(),4000,'CLOSED',300,'storeC');
INSERT INTO order_table(ORDER_NO,CUSTOMER_ID,DATED,ORDER_AMOUNT,ORDER_STATUS,STORE_ID,STORE_NAME) values(103,202,sysdate(),5000,'PLACED',300,'storeA');

INSERT INTO order_items(ORDER_ITEM_ID,ORDER_NO,PRICE,PRODUCT_ID,QUANTITY,STATUS) values(500,100,1000,400,20,'PLACED');
INSERT INTO order_items(ORDER_ITEM_ID,ORDER_NO,PRICE,PRODUCT_ID,QUANTITY,STATUS) values(501,100,2000,401,15,'CLOSED');
INSERT INTO order_items(ORDER_ITEM_ID,ORDER_NO,PRICE,PRODUCT_ID,QUANTITY,STATUS) values(502,101,3000,403,25,'SHIPPED');
INSERT INTO order_items(ORDER_ITEM_ID,ORDER_NO,PRICE,PRODUCT_ID,QUANTITY,STATUS) values(503,102,5000,402,30,'PLACED');


INSERT INTO product(PRODUCT_ID,IS_ACTIVE,PRICE,PRODUCT_NAME,RATING) values(400,TRUE,1000,'bat',5);
INSERT INTO product(PRODUCT_ID,IS_ACTIVE,PRICE,PRODUCT_NAME,RATING) values(401,TRUE,5000,'ball',4);
INSERT INTO product(PRODUCT_ID,IS_ACTIVE,PRICE,PRODUCT_NAME,RATING) values(402,TRUE,3000,'cap',2);
INSERT INTO product(PRODUCT_ID,IS_ACTIVE,PRICE,PRODUCT_NAME,RATING) values(403,TRUE,2000,'shirt',5);